# Generated by Django 5.2.12 on 2026-03-29 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_email_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_emails', to=settings.AUTH_USER_MODEL, verbose_name='Получатель (пользователь)'),
        ),
        migrations.AddField(
            model_name='email',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель (пользователь)'),
        ),
        migrations.AlterField(
            model_name='email',
            name='recipient',
            field=models.CharField(max_length=100, verbose_name='Получатель (текст)'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(max_length=100, verbose_name='Отправитель (текст)'),
        ),
    ]
